[workspace]
members = [
    "wenjin-wasm",
    "wenjin-derive",
    "wenjin",
    "wasm-testsuite/encoder",
    "wasm-testsuite/runner",
    #"wasi-types",
    #"examples/basic",
]
resolver = "2"


[profile.release]
debug = true

